// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta: dynamic(() => import("./Cta")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  image_and_text: dynamic(() => import("./ImageAndText")),
  testimonials: dynamic(() => import("./Testimonials")),
};
